// Code generated by tools/genwithcontext; DO NOT EDIT.

//go:build windows

package psadt

import (
	"context"

	"github.com/pedrostefanogv/go-psadt/types"
)

// AddEdgeExtensionWithContext runs AddEdgeExtension with an explicit context.
func (s *Session) AddEdgeExtensionWithContext(ctx context.Context, opts types.EdgeExtensionOptions) error {
	return s.WithContext(ctx).AddEdgeExtension(opts)
}

// AddFontWithContext runs AddFont with an explicit context.
func (s *Session) AddFontWithContext(ctx context.Context, name string) error {
	return s.WithContext(ctx).AddFont(name)
}

// AddModuleCallbackWithContext runs AddModuleCallback with an explicit context.
func (s *Session) AddModuleCallbackWithContext(ctx context.Context, opts types.ModuleCallbackOptions) error {
	return s.WithContext(ctx).AddModuleCallback(opts)
}

// BlockAppExecutionWithContext runs BlockAppExecution with an explicit context.
func (s *Session) BlockAppExecutionWithContext(ctx context.Context, processes []types.ProcessDefinition, position ...types.DialogPosition) error {
	return s.WithContext(ctx).BlockAppExecution(processes, position...)
}

// ClearModuleCallbackWithContext runs ClearModuleCallback with an explicit context.
func (s *Session) ClearModuleCallbackWithContext(ctx context.Context, hookPoint string) error {
	return s.WithContext(ctx).ClearModuleCallback(hookPoint)
}

// CloseInstallationProgressWithContext runs CloseInstallationProgress with an explicit context.
func (s *Session) CloseInstallationProgressWithContext(ctx context.Context) error {
	return s.WithContext(ctx).CloseInstallationProgress()
}

// ConvertRegistryPathWithContext runs ConvertRegistryPath with an explicit context.
func (s *Session) ConvertRegistryPathWithContext(ctx context.Context, registryPath string, toShort bool) (*types.RegistryPathInfo, error) {
	return s.WithContext(ctx).ConvertRegistryPath(registryPath, toShort)
}

// ConvertToNTAccountOrSIDWithContext runs ConvertToNTAccountOrSID with an explicit context.
func (s *Session) ConvertToNTAccountOrSIDWithContext(ctx context.Context, identity string, toSID bool) (string, error) {
	return s.WithContext(ctx).ConvertToNTAccountOrSID(identity, toSID)
}

// CopyContentToCacheWithContext runs CopyContentToCache with an explicit context.
func (s *Session) CopyContentToCacheWithContext(ctx context.Context, opts types.CopyContentToCacheOptions) (string, error) {
	return s.WithContext(ctx).CopyContentToCache(opts)
}

// CopyFileWithContext runs CopyFile with an explicit context.
func (s *Session) CopyFileWithContext(ctx context.Context, opts types.CopyFileOptions) error {
	return s.WithContext(ctx).CopyFile(opts)
}

// CopyFileToUserProfilesWithContext runs CopyFileToUserProfiles with an explicit context.
func (s *Session) CopyFileToUserProfilesWithContext(ctx context.Context, opts types.CopyFileToUserProfilesOptions) error {
	return s.WithContext(ctx).CopyFileToUserProfiles(opts)
}

// DisableTerminalServerInstallModeWithContext runs DisableTerminalServerInstallMode with an explicit context.
func (s *Session) DisableTerminalServerInstallModeWithContext(ctx context.Context) error {
	return s.WithContext(ctx).DisableTerminalServerInstallMode()
}

// DismountWimFileWithContext runs DismountWimFile with an explicit context.
func (s *Session) DismountWimFileWithContext(ctx context.Context, opts types.DismountWimOptions) error {
	return s.WithContext(ctx).DismountWimFile(opts)
}

// EnableTerminalServerInstallModeWithContext runs EnableTerminalServerInstallMode with an explicit context.
func (s *Session) EnableTerminalServerInstallModeWithContext(ctx context.Context) error {
	return s.WithContext(ctx).EnableTerminalServerInstallMode()
}

// ExportEnvironmentTableToSessionStateWithContext runs ExportEnvironmentTableToSessionState with an explicit context.
func (s *Session) ExportEnvironmentTableToSessionStateWithContext(ctx context.Context) error {
	return s.WithContext(ctx).ExportEnvironmentTableToSessionState()
}

// GetApplicationWithContext runs GetApplication with an explicit context.
func (s *Session) GetApplicationWithContext(ctx context.Context, opts types.GetApplicationOptions) ([]types.InstalledApplication, error) {
	return s.WithContext(ctx).GetApplication(opts)
}

// GetConfigWithContext runs GetConfig with an explicit context.
func (s *Session) GetConfigWithContext(ctx context.Context) (*types.ADTConfig, error) {
	return s.WithContext(ctx).GetConfig()
}

// GetDeferHistoryWithContext runs GetDeferHistory with an explicit context.
func (s *Session) GetDeferHistoryWithContext(ctx context.Context) (*types.DeferHistory, error) {
	return s.WithContext(ctx).GetDeferHistory()
}

// GetEnvironmentTableWithContext runs GetEnvironmentTable with an explicit context.
func (s *Session) GetEnvironmentTableWithContext(ctx context.Context) (types.EnvironmentTableInfo, error) {
	return s.WithContext(ctx).GetEnvironmentTable()
}

// GetEnvironmentVariableWithContext runs GetEnvironmentVariable with an explicit context.
func (s *Session) GetEnvironmentVariableWithContext(ctx context.Context, variable string, target ...types.EnvironmentVariableTarget) (string, error) {
	return s.WithContext(ctx).GetEnvironmentVariable(variable, target...)
}

// GetExecutableInfoWithContext runs GetExecutableInfo with an explicit context.
func (s *Session) GetExecutableInfoWithContext(ctx context.Context, filePath string) (*types.ExecutableInfo, error) {
	return s.WithContext(ctx).GetExecutableInfo(filePath)
}

// GetFileVersionWithContext runs GetFileVersion with an explicit context.
func (s *Session) GetFileVersionWithContext(ctx context.Context, filePath string) (string, error) {
	return s.WithContext(ctx).GetFileVersion(filePath)
}

// GetFreeDiskSpaceWithContext runs GetFreeDiskSpace with an explicit context.
func (s *Session) GetFreeDiskSpaceWithContext(ctx context.Context, drive ...string) (uint64, error) {
	return s.WithContext(ctx).GetFreeDiskSpace(drive...)
}

// GetIniSectionWithContext runs GetIniSection with an explicit context.
func (s *Session) GetIniSectionWithContext(ctx context.Context, filePath string, section string) (map[string]string, error) {
	return s.WithContext(ctx).GetIniSection(filePath, section)
}

// GetIniValueWithContext runs GetIniValue with an explicit context.
func (s *Session) GetIniValueWithContext(ctx context.Context, filePath string, section string, key string) (string, error) {
	return s.WithContext(ctx).GetIniValue(filePath, section, key)
}

// GetLoggedOnUserWithContext runs GetLoggedOnUser with an explicit context.
func (s *Session) GetLoggedOnUserWithContext(ctx context.Context) ([]types.LoggedOnUser, error) {
	return s.WithContext(ctx).GetLoggedOnUser()
}

// GetModuleCallbackWithContext runs GetModuleCallback with an explicit context.
func (s *Session) GetModuleCallbackWithContext(ctx context.Context, hookPoint ...string) ([]types.CallbackInfo, error) {
	return s.WithContext(ctx).GetModuleCallback(hookPoint...)
}

// GetMsiExitCodeMessageWithContext runs GetMsiExitCodeMessage with an explicit context.
func (s *Session) GetMsiExitCodeMessageWithContext(ctx context.Context, exitCode int) (string, error) {
	return s.WithContext(ctx).GetMsiExitCodeMessage(exitCode)
}

// GetMsiTablePropertyWithContext runs GetMsiTableProperty with an explicit context.
func (s *Session) GetMsiTablePropertyWithContext(ctx context.Context, opts types.MsiTableOptions) (map[string]string, error) {
	return s.WithContext(ctx).GetMsiTableProperty(opts)
}

// GetOperatingSystemInfoWithContext runs GetOperatingSystemInfo with an explicit context.
func (s *Session) GetOperatingSystemInfoWithContext(ctx context.Context) (*types.OSInfo, error) {
	return s.WithContext(ctx).GetOperatingSystemInfo()
}

// GetPEFileArchitectureWithContext runs GetPEFileArchitecture with an explicit context.
func (s *Session) GetPEFileArchitectureWithContext(ctx context.Context, filePath string) (string, error) {
	return s.WithContext(ctx).GetPEFileArchitecture(filePath)
}

// GetPendingRebootWithContext runs GetPendingReboot with an explicit context.
func (s *Session) GetPendingRebootWithContext(ctx context.Context) (*types.PendingRebootInfo, error) {
	return s.WithContext(ctx).GetPendingReboot()
}

// GetPowerShellProcessPathWithContext runs GetPowerShellProcessPath with an explicit context.
func (s *Session) GetPowerShellProcessPathWithContext(ctx context.Context) (*types.PowerShellProcessPathInfo, error) {
	return s.WithContext(ctx).GetPowerShellProcessPath()
}

// GetPresentationSettingsEnabledUsersWithContext runs GetPresentationSettingsEnabledUsers with an explicit context.
func (s *Session) GetPresentationSettingsEnabledUsersWithContext(ctx context.Context) ([]string, error) {
	return s.WithContext(ctx).GetPresentationSettingsEnabledUsers()
}

// GetRegistryKeyWithContext runs GetRegistryKey with an explicit context.
func (s *Session) GetRegistryKeyWithContext(ctx context.Context, opts types.GetRegistryKeyOptions) (interface{}, error) {
	return s.WithContext(ctx).GetRegistryKey(opts)
}

// GetRegistryKeyBinaryWithContext runs GetRegistryKeyBinary with an explicit context.
func (s *Session) GetRegistryKeyBinaryWithContext(ctx context.Context, key string, name string) ([]byte, error) {
	return s.WithContext(ctx).GetRegistryKeyBinary(key, name)
}

// GetRegistryKeyDWordWithContext runs GetRegistryKeyDWord with an explicit context.
func (s *Session) GetRegistryKeyDWordWithContext(ctx context.Context, key string, name string) (uint32, error) {
	return s.WithContext(ctx).GetRegistryKeyDWord(key, name)
}

// GetRegistryKeyMultiStringWithContext runs GetRegistryKeyMultiString with an explicit context.
func (s *Session) GetRegistryKeyMultiStringWithContext(ctx context.Context, key string, name string) ([]string, error) {
	return s.WithContext(ctx).GetRegistryKeyMultiString(key, name)
}

// GetRegistryKeyQWordWithContext runs GetRegistryKeyQWord with an explicit context.
func (s *Session) GetRegistryKeyQWordWithContext(ctx context.Context, key string, name string) (uint64, error) {
	return s.WithContext(ctx).GetRegistryKeyQWord(key, name)
}

// GetRegistryKeyStringWithContext runs GetRegistryKeyString with an explicit context.
func (s *Session) GetRegistryKeyStringWithContext(ctx context.Context, key string, name string) (string, error) {
	return s.WithContext(ctx).GetRegistryKeyString(key, name)
}

// GetRunningProcessesWithContext runs GetRunningProcesses with an explicit context.
func (s *Session) GetRunningProcessesWithContext(ctx context.Context, processNames []string) ([]types.RunningProcess, error) {
	return s.WithContext(ctx).GetRunningProcesses(processNames)
}

// GetServiceStartModeWithContext runs GetServiceStartMode with an explicit context.
func (s *Session) GetServiceStartModeWithContext(ctx context.Context, name string) (types.ServiceStartMode, error) {
	return s.WithContext(ctx).GetServiceStartMode(name)
}

// GetSessionWithContext runs GetSession with an explicit context.
func (s *Session) GetSessionWithContext(ctx context.Context) (*types.SessionProperties, error) {
	return s.WithContext(ctx).GetSession()
}

// GetShortcutWithContext runs GetShortcut with an explicit context.
func (s *Session) GetShortcutWithContext(ctx context.Context, path string) (*types.ShortcutInfo, error) {
	return s.WithContext(ctx).GetShortcut(path)
}

// GetStringTableWithContext runs GetStringTable with an explicit context.
func (s *Session) GetStringTableWithContext(ctx context.Context) (*types.ADTStringTable, error) {
	return s.WithContext(ctx).GetStringTable()
}

// GetUniversalDateWithContext runs GetUniversalDate with an explicit context.
func (s *Session) GetUniversalDateWithContext(ctx context.Context, dateTime ...string) (string, error) {
	return s.WithContext(ctx).GetUniversalDate(dateTime...)
}

// GetUserNotificationStateWithContext runs GetUserNotificationState with an explicit context.
func (s *Session) GetUserNotificationStateWithContext(ctx context.Context) (string, error) {
	return s.WithContext(ctx).GetUserNotificationState()
}

// GetUserProfilesWithContext runs GetUserProfiles with an explicit context.
func (s *Session) GetUserProfilesWithContext(ctx context.Context, opts ...types.UserProfileOptions) ([]types.UserProfile, error) {
	return s.WithContext(ctx).GetUserProfiles(opts...)
}

// GetUserToastNotificationModeWithContext runs GetUserToastNotificationMode with an explicit context.
func (s *Session) GetUserToastNotificationModeWithContext(ctx context.Context) (string, error) {
	return s.WithContext(ctx).GetUserToastNotificationMode()
}

// GetWindowTitleWithContext runs GetWindowTitle with an explicit context.
func (s *Session) GetWindowTitleWithContext(ctx context.Context, opts types.GetWindowTitleOptions) ([]types.WindowTitle, error) {
	return s.WithContext(ctx).GetWindowTitle(opts)
}

// InstallMSUpdatesWithContext runs InstallMSUpdates with an explicit context.
func (s *Session) InstallMSUpdatesWithContext(ctx context.Context, directory string) error {
	return s.WithContext(ctx).InstallMSUpdates(directory)
}

// InstallSCCMSoftwareUpdatesWithContext runs InstallSCCMSoftwareUpdates with an explicit context.
func (s *Session) InstallSCCMSoftwareUpdatesWithContext(ctx context.Context) error {
	return s.WithContext(ctx).InstallSCCMSoftwareUpdates()
}

// InvokeAllUsersRegistryActionWithContext runs InvokeAllUsersRegistryAction with an explicit context.
func (s *Session) InvokeAllUsersRegistryActionWithContext(ctx context.Context, scriptBlock string, opts ...types.AllUsersRegistryOptions) error {
	return s.WithContext(ctx).InvokeAllUsersRegistryAction(scriptBlock, opts...)
}

// InvokeCommandWithRetriesWithContext runs InvokeCommandWithRetries with an explicit context.
func (s *Session) InvokeCommandWithRetriesWithContext(ctx context.Context, scriptBlock string, opts ...types.RetryOptions) error {
	return s.WithContext(ctx).InvokeCommandWithRetries(scriptBlock, opts...)
}

// InvokeRegSvr32WithContext runs InvokeRegSvr32 with an explicit context.
func (s *Session) InvokeRegSvr32WithContext(ctx context.Context, opts types.RegSvr32Options) error {
	return s.WithContext(ctx).InvokeRegSvr32(opts)
}

// InvokeSCCMTaskWithContext runs InvokeSCCMTask with an explicit context.
func (s *Session) InvokeSCCMTaskWithContext(ctx context.Context, opts types.SCCMTaskOptions) error {
	return s.WithContext(ctx).InvokeSCCMTask(opts)
}

// MountWimFileWithContext runs MountWimFile with an explicit context.
func (s *Session) MountWimFileWithContext(ctx context.Context, opts types.MountWimOptions) (string, error) {
	return s.WithContext(ctx).MountWimFile(opts)
}

// NewFolderWithContext runs NewFolder with an explicit context.
func (s *Session) NewFolderWithContext(ctx context.Context, path string) error {
	return s.WithContext(ctx).NewFolder(path)
}

// NewLogFileNameWithContext runs NewLogFileName with an explicit context.
func (s *Session) NewLogFileNameWithContext(ctx context.Context, opts ...types.LogFileNameOptions) (string, error) {
	return s.WithContext(ctx).NewLogFileName(opts...)
}

// NewMsiTransformWithContext runs NewMsiTransform with an explicit context.
func (s *Session) NewMsiTransformWithContext(ctx context.Context, opts types.MsiTransformOptions) error {
	return s.WithContext(ctx).NewMsiTransform(opts)
}

// NewShortcutWithContext runs NewShortcut with an explicit context.
func (s *Session) NewShortcutWithContext(ctx context.Context, opts types.NewShortcutOptions) error {
	return s.WithContext(ctx).NewShortcut(opts)
}

// NewTemplateWithContext runs NewTemplate with an explicit context.
func (s *Session) NewTemplateWithContext(ctx context.Context, destination string) error {
	return s.WithContext(ctx).NewTemplate(destination)
}

// NewZipFileWithContext runs NewZipFile with an explicit context.
func (s *Session) NewZipFileWithContext(ctx context.Context, opts types.NewZipOptions) error {
	return s.WithContext(ctx).NewZipFile(opts)
}

// NotifyInfoWithContext runs NotifyInfo with an explicit context.
func (s *Session) NotifyInfoWithContext(ctx context.Context, title string, message string) error {
	return s.WithContext(ctx).NotifyInfo(title, message)
}

// NotifyProgressWithContext runs NotifyProgress with an explicit context.
func (s *Session) NotifyProgressWithContext(ctx context.Context, appName string, statusMessage string) error {
	return s.WithContext(ctx).NotifyProgress(appName, statusMessage)
}

// NotifyUpdateWithContext runs NotifyUpdate with an explicit context.
func (s *Session) NotifyUpdateWithContext(ctx context.Context, n UpdateNotification) error {
	return s.WithContext(ctx).NotifyUpdate(n)
}

// OutPowerShellEncodedCommandWithContext runs OutPowerShellEncodedCommand with an explicit context.
func (s *Session) OutPowerShellEncodedCommandWithContext(ctx context.Context, scriptBlock string) (string, error) {
	return s.WithContext(ctx).OutPowerShellEncodedCommand(scriptBlock)
}

// RegisterDllWithContext runs RegisterDll with an explicit context.
func (s *Session) RegisterDllWithContext(ctx context.Context, filePath string) error {
	return s.WithContext(ctx).RegisterDll(filePath)
}

// RemoveContentFromCacheWithContext runs RemoveContentFromCache with an explicit context.
func (s *Session) RemoveContentFromCacheWithContext(ctx context.Context, opts types.RemoveContentFromCacheOptions) error {
	return s.WithContext(ctx).RemoveContentFromCache(opts)
}

// RemoveDesktopShortcutWithContext runs RemoveDesktopShortcut with an explicit context.
func (s *Session) RemoveDesktopShortcutWithContext(ctx context.Context, name string, allUsers bool) error {
	return s.WithContext(ctx).RemoveDesktopShortcut(name, allUsers)
}

// RemoveEdgeExtensionWithContext runs RemoveEdgeExtension with an explicit context.
func (s *Session) RemoveEdgeExtensionWithContext(ctx context.Context, extensionID string) error {
	return s.WithContext(ctx).RemoveEdgeExtension(extensionID)
}

// RemoveEnvironmentVariableWithContext runs RemoveEnvironmentVariable with an explicit context.
func (s *Session) RemoveEnvironmentVariableWithContext(ctx context.Context, variable string, target ...types.EnvironmentVariableTarget) error {
	return s.WithContext(ctx).RemoveEnvironmentVariable(variable, target...)
}

// RemoveFileWithContext runs RemoveFile with an explicit context.
func (s *Session) RemoveFileWithContext(ctx context.Context, opts types.RemoveFileOptions) error {
	return s.WithContext(ctx).RemoveFile(opts)
}

// RemoveFileFromUserProfilesWithContext runs RemoveFileFromUserProfiles with an explicit context.
func (s *Session) RemoveFileFromUserProfilesWithContext(ctx context.Context, opts types.RemoveFileFromUserProfilesOptions) error {
	return s.WithContext(ctx).RemoveFileFromUserProfiles(opts)
}

// RemoveFolderWithContext runs RemoveFolder with an explicit context.
func (s *Session) RemoveFolderWithContext(ctx context.Context, opts types.RemoveFolderOptions) error {
	return s.WithContext(ctx).RemoveFolder(opts)
}

// RemoveFontWithContext runs RemoveFont with an explicit context.
func (s *Session) RemoveFontWithContext(ctx context.Context, name string) error {
	return s.WithContext(ctx).RemoveFont(name)
}

// RemoveIniSectionWithContext runs RemoveIniSection with an explicit context.
func (s *Session) RemoveIniSectionWithContext(ctx context.Context, filePath string, section string) error {
	return s.WithContext(ctx).RemoveIniSection(filePath, section)
}

// RemoveIniValueWithContext runs RemoveIniValue with an explicit context.
func (s *Session) RemoveIniValueWithContext(ctx context.Context, filePath string, section string, key ...string) error {
	return s.WithContext(ctx).RemoveIniValue(filePath, section, key...)
}

// RemoveInvalidFileNameCharsWithContext runs RemoveInvalidFileNameChars with an explicit context.
func (s *Session) RemoveInvalidFileNameCharsWithContext(ctx context.Context, name string) (string, error) {
	return s.WithContext(ctx).RemoveInvalidFileNameChars(name)
}

// RemoveModuleCallbackWithContext runs RemoveModuleCallback with an explicit context.
func (s *Session) RemoveModuleCallbackWithContext(ctx context.Context, name string, hookPoint string) error {
	return s.WithContext(ctx).RemoveModuleCallback(name, hookPoint)
}

// RemoveRegistryKeyWithContext runs RemoveRegistryKey with an explicit context.
func (s *Session) RemoveRegistryKeyWithContext(ctx context.Context, opts types.RemoveRegistryKeyOptions) error {
	return s.WithContext(ctx).RemoveRegistryKey(opts)
}

// ResetDeferHistoryWithContext runs ResetDeferHistory with an explicit context.
func (s *Session) ResetDeferHistoryWithContext(ctx context.Context) error {
	return s.WithContext(ctx).ResetDeferHistory()
}

// SendKeysWithContext runs SendKeys with an explicit context.
func (s *Session) SendKeysWithContext(ctx context.Context, opts types.SendKeysOptions) error {
	return s.WithContext(ctx).SendKeys(opts)
}

// SetActiveSetupWithContext runs SetActiveSetup with an explicit context.
func (s *Session) SetActiveSetupWithContext(ctx context.Context, opts types.ActiveSetupOptions) error {
	return s.WithContext(ctx).SetActiveSetup(opts)
}

// SetDeferHistoryWithContext runs SetDeferHistory with an explicit context.
func (s *Session) SetDeferHistoryWithContext(ctx context.Context, opts types.DeferHistory) error {
	return s.WithContext(ctx).SetDeferHistory(opts)
}

// SetEnvironmentVariableWithContext runs SetEnvironmentVariable with an explicit context.
func (s *Session) SetEnvironmentVariableWithContext(ctx context.Context, variable string, value string, target ...types.EnvironmentVariableTarget) error {
	return s.WithContext(ctx).SetEnvironmentVariable(variable, value, target...)
}

// SetIniSectionWithContext runs SetIniSection with an explicit context.
func (s *Session) SetIniSectionWithContext(ctx context.Context, filePath string, section string, content map[string]string) error {
	return s.WithContext(ctx).SetIniSection(filePath, section, content)
}

// SetIniValueWithContext runs SetIniValue with an explicit context.
func (s *Session) SetIniValueWithContext(ctx context.Context, filePath string, section string, key string, value string) error {
	return s.WithContext(ctx).SetIniValue(filePath, section, key, value)
}

// SetItemPermissionWithContext runs SetItemPermission with an explicit context.
func (s *Session) SetItemPermissionWithContext(ctx context.Context, opts types.ItemPermissionOptions) error {
	return s.WithContext(ctx).SetItemPermission(opts)
}

// SetMsiPropertyWithContext runs SetMsiProperty with an explicit context.
func (s *Session) SetMsiPropertyWithContext(ctx context.Context, opts types.SetMsiPropertyOptions) error {
	return s.WithContext(ctx).SetMsiProperty(opts)
}

// SetPowerShellCultureWithContext runs SetPowerShellCulture with an explicit context.
func (s *Session) SetPowerShellCultureWithContext(ctx context.Context, cultureName string) error {
	return s.WithContext(ctx).SetPowerShellCulture(cultureName)
}

// SetRegistryKeyWithContext runs SetRegistryKey with an explicit context.
func (s *Session) SetRegistryKeyWithContext(ctx context.Context, opts types.SetRegistryKeyOptions) error {
	return s.WithContext(ctx).SetRegistryKey(opts)
}

// SetServiceStartModeWithContext runs SetServiceStartMode with an explicit context.
func (s *Session) SetServiceStartModeWithContext(ctx context.Context, name string, mode types.ServiceStartMode) error {
	return s.WithContext(ctx).SetServiceStartMode(name, mode)
}

// SetShortcutWithContext runs SetShortcut with an explicit context.
func (s *Session) SetShortcutWithContext(ctx context.Context, opts types.SetShortcutOptions) error {
	return s.WithContext(ctx).SetShortcut(opts)
}

// ShowBalloonTipWithContext runs ShowBalloonTip with an explicit context.
func (s *Session) ShowBalloonTipWithContext(ctx context.Context, opts types.BalloonTipOptions) error {
	return s.WithContext(ctx).ShowBalloonTip(opts)
}

// ShowDialogBoxWithContext runs ShowDialogBox with an explicit context.
func (s *Session) ShowDialogBoxWithContext(ctx context.Context, opts types.DialogBoxOptions) (types.DialogBoxResult, error) {
	return s.WithContext(ctx).ShowDialogBox(opts)
}

// ShowHelpConsoleWithContext runs ShowHelpConsole with an explicit context.
func (s *Session) ShowHelpConsoleWithContext(ctx context.Context) error {
	return s.WithContext(ctx).ShowHelpConsole()
}

// ShowInstallationProgressWithContext runs ShowInstallationProgress with an explicit context.
func (s *Session) ShowInstallationProgressWithContext(ctx context.Context, opts types.ProgressOptions) error {
	return s.WithContext(ctx).ShowInstallationProgress(opts)
}

// ShowInstallationPromptWithContext runs ShowInstallationPrompt with an explicit context.
func (s *Session) ShowInstallationPromptWithContext(ctx context.Context, opts types.PromptOptions) (*types.PromptResult, error) {
	return s.WithContext(ctx).ShowInstallationPrompt(opts)
}

// ShowInstallationRestartPromptWithContext runs ShowInstallationRestartPrompt with an explicit context.
func (s *Session) ShowInstallationRestartPromptWithContext(ctx context.Context, opts types.RestartPromptOptions) error {
	return s.WithContext(ctx).ShowInstallationRestartPrompt(opts)
}

// ShowInstallationWelcomeWithContext runs ShowInstallationWelcome with an explicit context.
func (s *Session) ShowInstallationWelcomeWithContext(ctx context.Context, opts types.WelcomeOptions) error {
	return s.WithContext(ctx).ShowInstallationWelcome(opts)
}

// StartMsiProcessWithContext runs StartMsiProcess with an explicit context.
func (s *Session) StartMsiProcessWithContext(ctx context.Context, opts types.MsiProcessOptions) (*types.ProcessResult, error) {
	return s.WithContext(ctx).StartMsiProcess(opts)
}

// StartMsiProcessAsUserWithContext runs StartMsiProcessAsUser with an explicit context.
func (s *Session) StartMsiProcessAsUserWithContext(ctx context.Context, opts types.MsiProcessAsUserOptions) (*types.ProcessResult, error) {
	return s.WithContext(ctx).StartMsiProcessAsUser(opts)
}

// StartMspProcessWithContext runs StartMspProcess with an explicit context.
func (s *Session) StartMspProcessWithContext(ctx context.Context, opts types.MspProcessOptions) (*types.ProcessResult, error) {
	return s.WithContext(ctx).StartMspProcess(opts)
}

// StartMspProcessAsUserWithContext runs StartMspProcessAsUser with an explicit context.
func (s *Session) StartMspProcessAsUserWithContext(ctx context.Context, opts types.MspProcessAsUserOptions) (*types.ProcessResult, error) {
	return s.WithContext(ctx).StartMspProcessAsUser(opts)
}

// StartProcessWithContext runs StartProcess with an explicit context.
func (s *Session) StartProcessWithContext(ctx context.Context, opts types.StartProcessOptions) (*types.ProcessResult, error) {
	return s.WithContext(ctx).StartProcess(opts)
}

// StartProcessAsUserWithContext runs StartProcessAsUser with an explicit context.
func (s *Session) StartProcessAsUserWithContext(ctx context.Context, opts types.StartProcessAsUserOptions) (*types.ProcessResult, error) {
	return s.WithContext(ctx).StartProcessAsUser(opts)
}

// StartServiceAndDependenciesWithContext runs StartServiceAndDependencies with an explicit context.
func (s *Session) StartServiceAndDependenciesWithContext(ctx context.Context, opts types.ServiceOptions) error {
	return s.WithContext(ctx).StartServiceAndDependencies(opts)
}

// StopServiceAndDependenciesWithContext runs StopServiceAndDependencies with an explicit context.
func (s *Session) StopServiceAndDependenciesWithContext(ctx context.Context, opts types.ServiceOptions) error {
	return s.WithContext(ctx).StopServiceAndDependencies(opts)
}

// TestBatteryWithContext runs TestBattery with an explicit context.
func (s *Session) TestBatteryWithContext(ctx context.Context) (*types.BatteryInfo, error) {
	return s.WithContext(ctx).TestBattery()
}

// TestCallerIsAdminWithContext runs TestCallerIsAdmin with an explicit context.
func (s *Session) TestCallerIsAdminWithContext(ctx context.Context) (bool, error) {
	return s.WithContext(ctx).TestCallerIsAdmin()
}

// TestEspActiveWithContext runs TestEspActive with an explicit context.
func (s *Session) TestEspActiveWithContext(ctx context.Context) (bool, error) {
	return s.WithContext(ctx).TestEspActive()
}

// TestIsLaptopWithContext runs TestIsLaptop with an explicit context.
func (s *Session) TestIsLaptopWithContext(ctx context.Context) (bool, error) {
	return s.WithContext(ctx).TestIsLaptop()
}

// TestMSUpdatesWithContext runs TestMSUpdates with an explicit context.
func (s *Session) TestMSUpdatesWithContext(ctx context.Context, kbNumber string) (bool, error) {
	return s.WithContext(ctx).TestMSUpdates(kbNumber)
}

// TestMicrophoneInUseWithContext runs TestMicrophoneInUse with an explicit context.
func (s *Session) TestMicrophoneInUseWithContext(ctx context.Context) (bool, error) {
	return s.WithContext(ctx).TestMicrophoneInUse()
}

// TestModuleInitializedWithContext runs TestModuleInitialized with an explicit context.
func (s *Session) TestModuleInitializedWithContext(ctx context.Context) (bool, error) {
	return s.WithContext(ctx).TestModuleInitialized()
}

// TestMutexAvailabilityWithContext runs TestMutexAvailability with an explicit context.
func (s *Session) TestMutexAvailabilityWithContext(ctx context.Context, mutexName string) (bool, error) {
	return s.WithContext(ctx).TestMutexAvailability(mutexName)
}

// TestNetworkConnectionWithContext runs TestNetworkConnection with an explicit context.
func (s *Session) TestNetworkConnectionWithContext(ctx context.Context) (bool, error) {
	return s.WithContext(ctx).TestNetworkConnection()
}

// TestOobeCompletedWithContext runs TestOobeCompleted with an explicit context.
func (s *Session) TestOobeCompletedWithContext(ctx context.Context) (bool, error) {
	return s.WithContext(ctx).TestOobeCompleted()
}

// TestPowerPointWithContext runs TestPowerPoint with an explicit context.
func (s *Session) TestPowerPointWithContext(ctx context.Context) (bool, error) {
	return s.WithContext(ctx).TestPowerPoint()
}

// TestRegistryValueWithContext runs TestRegistryValue with an explicit context.
func (s *Session) TestRegistryValueWithContext(ctx context.Context, opts types.TestRegistryValueOptions) (bool, error) {
	return s.WithContext(ctx).TestRegistryValue(opts)
}

// TestServiceExistsWithContext runs TestServiceExists with an explicit context.
func (s *Session) TestServiceExistsWithContext(ctx context.Context, name string) (bool, error) {
	return s.WithContext(ctx).TestServiceExists(name)
}

// TestSessionActiveWithContext runs TestSessionActive with an explicit context.
func (s *Session) TestSessionActiveWithContext(ctx context.Context) (bool, error) {
	return s.WithContext(ctx).TestSessionActive()
}

// TestUserInFocusModeWithContext runs TestUserInFocusMode with an explicit context.
func (s *Session) TestUserInFocusModeWithContext(ctx context.Context) (bool, error) {
	return s.WithContext(ctx).TestUserInFocusMode()
}

// TestUserIsBusyWithContext runs TestUserIsBusy with an explicit context.
func (s *Session) TestUserIsBusyWithContext(ctx context.Context) (bool, error) {
	return s.WithContext(ctx).TestUserIsBusy()
}

// UnblockAppExecutionWithContext runs UnblockAppExecution with an explicit context.
func (s *Session) UnblockAppExecutionWithContext(ctx context.Context) error {
	return s.WithContext(ctx).UnblockAppExecution()
}

// UninstallApplicationWithContext runs UninstallApplication with an explicit context.
func (s *Session) UninstallApplicationWithContext(ctx context.Context, opts types.UninstallApplicationOptions) error {
	return s.WithContext(ctx).UninstallApplication(opts)
}

// UnregisterDllWithContext runs UnregisterDll with an explicit context.
func (s *Session) UnregisterDllWithContext(ctx context.Context, filePath string) error {
	return s.WithContext(ctx).UnregisterDll(filePath)
}

// UpdateDesktopWithContext runs UpdateDesktop with an explicit context.
func (s *Session) UpdateDesktopWithContext(ctx context.Context) error {
	return s.WithContext(ctx).UpdateDesktop()
}

// UpdateEnvironmentPsProviderWithContext runs UpdateEnvironmentPsProvider with an explicit context.
func (s *Session) UpdateEnvironmentPsProviderWithContext(ctx context.Context) error {
	return s.WithContext(ctx).UpdateEnvironmentPsProvider()
}

// UpdateGroupPolicyWithContext runs UpdateGroupPolicy with an explicit context.
func (s *Session) UpdateGroupPolicyWithContext(ctx context.Context) error {
	return s.WithContext(ctx).UpdateGroupPolicy()
}

// WriteLogEntryWithContext runs WriteLogEntry with an explicit context.
func (s *Session) WriteLogEntryWithContext(ctx context.Context, opts types.LogEntryOptions) error {
	return s.WithContext(ctx).WriteLogEntry(opts)
}

// WriteLogEntryErrorWithContext runs WriteLogEntryError with an explicit context.
func (s *Session) WriteLogEntryErrorWithContext(ctx context.Context, message string, source string) error {
	return s.WithContext(ctx).WriteLogEntryError(message, source)
}

// WriteLogEntryInfoWithContext runs WriteLogEntryInfo with an explicit context.
func (s *Session) WriteLogEntryInfoWithContext(ctx context.Context, message string, source string) error {
	return s.WithContext(ctx).WriteLogEntryInfo(message, source)
}

// WriteLogEntryWarningWithContext runs WriteLogEntryWarning with an explicit context.
func (s *Session) WriteLogEntryWarningWithContext(ctx context.Context, message string, source string) error {
	return s.WithContext(ctx).WriteLogEntryWarning(message, source)
}
