// Command genwithcontext generates *WithContext variants for all exported
// Session methods that (a) don't already have one and (b) don't take a
// context.Context themselves. The generated variants delegate through
// Session.WithContext, which propagates the caller's deadline/cancellation
// to every nested getContext() call.
//
// Usage (from the repository root):
//
//	go run ./tools/genwithcontext
//
// Output: withcontext_gen.go (do not edit by hand).
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const receiverType = "Session"

var skipNames = map[string]bool{
	"WithContext": true,
	"OnClose":     true, // hooks, not command executions
	"OnError":     true,
	"LiveOutput":  true, // channel accessor
}

type method struct {
	name    string
	params  string // expanded parameter list (name type, ...)
	args    string // call argument list
	results string // raw results text ("" if none)
}

type fileInfo struct {
	file *ast.File
	src  []byte
}

func main() {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, ".", func(fi os.FileInfo) bool {
		return !fi.IsDir() && !strings.HasSuffix(fi.Name(), "_test.go") &&
			fi.Name() != "withcontext_gen.go"
	}, 0)
	if err != nil {
		fatal("parse: %v", err)
	}
	pkg, ok := pkgs["psadt"]
	if !ok {
		fatal("package psadt not found in current directory")
	}

	// Pass 1: read sources and collect names that already have variants.
	existing := map[string]bool{}
	files := make([]fileInfo, 0, len(pkg.Files))
	for fname, file := range pkg.Files {
		src, err := os.ReadFile(filepath.Join(".", fname))
		if err != nil {
			fatal("read %s: %v", fname, err)
		}
		files = append(files, fileInfo{file: file, src: src})
		for _, decl := range file.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || !isSessionRecv(fd) {
				continue
			}
			name := fd.Name.Name
			if strings.HasSuffix(name, "WithContext") {
				existing[strings.TrimSuffix(name, "WithContext")] = true
			}
		}
	}

	// Pass 2: collect methods needing variants.
	var targets []method
	for _, fi := range files {
		for _, decl := range fi.file.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || !isSessionRecv(fd) {
				continue
			}
			name := fd.Name.Name
			if !ast.IsExported(name) || skipNames[name] || existing[name] {
				continue
			}
			if fd.Type.Params == nil || takesContext(fd) {
				continue
			}

			m := method{name: name}
			var params, args []string
			idx := 0
			for _, field := range fd.Type.Params.List {
				typeText := text(fset, fi, field.Type)
				if ell, isEll := field.Type.(*ast.Ellipsis); isEll {
					typeText = "..." + text(fset, fi, ell.Elt)
				}
				names := field.Names
				if len(names) == 0 {
					names = []*ast.Ident{ast.NewIdent(fmt.Sprintf("arg%d", idx))}
				}
				for _, n := range names {
					params = append(params, n.Name+" "+typeText)
					if strings.HasPrefix(typeText, "...") {
						args = append(args, n.Name+"...")
					} else {
						args = append(args, n.Name)
					}
					idx++
				}
			}
			m.params = strings.Join(params, ", ")
			m.args = strings.Join(args, ", ")
			if fd.Type.Results != nil {
				m.results = text(fset, fi, fd.Type.Results)
			}
			targets = append(targets, m)
		}
	}

	sort.Slice(targets, func(i, j int) bool { return targets[i].name < targets[j].name })

	var body bytes.Buffer
	for _, m := range targets {
		results := ""
		if m.results != "" {
			results = " " + m.results
		}
		fmt.Fprintf(&body, "// %sWithContext runs %s with an explicit context.\n", m.name, m.name)
		if m.params == "" {
			fmt.Fprintf(&body, "func (s *Session) %sWithContext(ctx context.Context)%s {\n", m.name, results)
		} else {
			fmt.Fprintf(&body, "func (s *Session) %sWithContext(ctx context.Context, %s)%s {\n", m.name, m.params, results)
		}
		fmt.Fprintf(&body, "\treturn s.WithContext(ctx).%s(%s)\n}\n\n", m.name, m.args)
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by tools/genwithcontext; DO NOT EDIT.")
	out.WriteString("\n\n//go:build windows\n\npackage psadt\n\n")
	if strings.Contains(body.String(), "types.") {
		out.WriteString("import (\n\t\"context\"\n\n\t\"github.com/pedrostefanogv/go-psadt/types\"\n)\n\n")
	} else {
		out.WriteString("import \"context\"\n\n")
	}
	out.Write(body.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		fatal("format generated source: %v\n--- source ---\n%s", err, out.String())
	}
	if err := os.WriteFile("withcontext_gen.go", formatted, 0o644); err != nil {
		fatal("write withcontext_gen.go: %v", err)
	}
	fmt.Printf("generated %d WithContext variants in withcontext_gen.go\n", len(targets))
}

func isSessionRecv(fd *ast.FuncDecl) bool {
	if fd.Recv == nil || len(fd.Recv.List) == 0 {
		return false
	}
	star, ok := fd.Recv.List[0].Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	ident, ok := star.X.(*ast.Ident)
	return ok && ident.Name == receiverType
}

// takesContext reports whether the method's first parameter is context.Context.
func takesContext(fd *ast.FuncDecl) bool {
	if fd.Type.Params == nil || len(fd.Type.Params.List) == 0 {
		return false
	}
	first := fd.Type.Params.List[0]
	if sel, ok := first.Type.(*ast.SelectorExpr); ok {
		if x, ok := sel.X.(*ast.Ident); ok && x.Name == "context" && sel.Sel.Name == "Context" {
			return true
		}
	}
	return false
}

// text returns the exact source text of a node.
func text(fset *token.FileSet, fi fileInfo, n ast.Node) string {
	start := fset.Position(n.Pos()).Offset
	end := fset.Position(n.End()).Offset
	return string(fi.src[start:end])
}

func fatal(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "genwithcontext: "+format+"\n", args...)
	os.Exit(1)
}
